/* project Euler #2
 * Each new term in the Fibonacci sequence is generated by adding
 * the previous two terms. By starting with 1 and 2, the first 10
 * terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values
 * do not exceed four million, find the sum of the even-valued
 * terms.
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

int main()
{
    uint64_t a = 1, b = 2;
    int i, n = 0;
    uint64_t acum = 0;

    for (i = 0; b < 4000000; i++) {
        uint64_t c = a + b;
        if (i % 3 == 0) {
            printf("%s%d", n++ ? " + " : "", b);
            acum += b;
        } /* if */
        a = b; b = c;
    } /* for */
    printf(" = %lld\n", acum);

    exit(EXIT_SUCCESS);
} /* main */
